#ifndef CONSTANT_H

#define CONSTANT_H

#define QUANTITY_DIGIT_IN_NUMBER 4
#define INTERVAL_FROM_ONE_TO_NINE 9
#define MAX_QUANTITY_ATTEMPT 3024
#define INDEX_BULLS 0
#define INDEX_COWS 1
#define LOOSE 0
#define WIN 1
#define SIZE_ARRAY_BULLS_AND_COWS 2

#endif